# Generated by Django 3.0.4 on 2020-08-07 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UrlData',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('html_content', models.TextField(blank=True, null=True)),
            ],
        ),
    ]
