# Generated by Django 3.1 on 2020-09-11 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('path_finder', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Link',
            fields=[
                ('id', models.IntegerField(default=1, primary_key=True, serialize=False)),
                ('url', models.TextField(blank=True, null=True)),
                ('recursive_occurrence', models.IntegerField(default=0)),
                ('non_recursive_occurrence', models.IntegerField(default=0)),
            ],
        ),
    ]
